import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sfs
 */
public class Add extends javax.swing.JFrame {

    /**
     * Creates new form Add
     */
    public Add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ntf = new javax.swing.JTextField();
        mntf = new javax.swing.JTextField();
        atf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ftf = new javax.swing.JTextField();
        mtf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sntf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dojtf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        etf = new javax.swing.JRadioButton();
        ttf = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        addbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        stf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        subcb = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        clbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(14, 31, 156));
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(14, 31, 156));
        jLabel2.setText("Mobile No.");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(14, 31, 156));
        jLabel3.setText("Address");

        ntf.setFont(new java.awt.Font("URW Chancery L", 3, 20)); // NOI18N

        mntf.setFont(new java.awt.Font("URW Chancery L", 3, 20)); // NOI18N
        mntf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntfActionPerformed(evt);
            }
        });

        atf.setFont(new java.awt.Font("URW Chancery L", 3, 20)); // NOI18N
        atf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atfActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(14, 31, 156));
        jLabel4.setText("Father Name");

        jLabel5.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(14, 31, 156));
        jLabel5.setText("Mother Name");

        ftf.setFont(new java.awt.Font("URW Chancery L", 3, 20)); // NOI18N

        mtf.setFont(new java.awt.Font("URW Chancery L", 3, 20)); // NOI18N

        jLabel6.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(14, 31, 156));
        jLabel6.setText("School Name");

        sntf.setFont(new java.awt.Font("URW Chancery L", 3, 20)); // NOI18N
        sntf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sntfActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(14, 31, 156));
        jLabel7.setText("Date Of Joining");

        dojtf.setFont(new java.awt.Font("URW Chancery L", 3, 20)); // NOI18N
        dojtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dojtfActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(14, 31, 156));
        jLabel8.setText("Class");

        buttonGroup1.add(etf);
        etf.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        etf.setForeground(new java.awt.Color(14, 31, 156));
        etf.setText("11th");
        etf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etfActionPerformed(evt);
            }
        });

        buttonGroup1.add(ttf);
        ttf.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        ttf.setForeground(new java.awt.Color(14, 31, 156));
        ttf.setText("12th");
        ttf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttfActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("URW Chancery L", 3, 40)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(239, 27, 127));
        jLabel9.setText("DC Coaching Classes");

        addbtn.setFont(new java.awt.Font("Bodoni MT Black", 3, 16)); // NOI18N
        addbtn.setForeground(new java.awt.Color(47, 47, 208));
        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        backbtn.setFont(new java.awt.Font("Bodoni MT Black", 3, 16)); // NOI18N
        backbtn.setForeground(new java.awt.Color(47, 47, 208));
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        exitbtn.setFont(new java.awt.Font("Bodoni MT Black", 3, 16)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(47, 47, 208));
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(66, 50, 176));
        jLabel10.setText("Sch_No.");

        stf.setFont(new java.awt.Font("URW Chancery L", 3, 20)); // NOI18N

        jLabel11.setFont(new java.awt.Font("DejaVu Sans Light", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(32, 66, 118));
        jLabel11.setText("Subject");

        subcb.setFont(new java.awt.Font("URW Palladio L", 3, 18)); // NOI18N
        subcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Science with PE", "Science with IP", "Commers with Maths", "Commers with IP" }));
        subcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subcbActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(201, 33, 33));
        jSeparator2.setForeground(new java.awt.Color(241, 64, 13));
        jSeparator2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        clbtn.setFont(new java.awt.Font("Bodoni MT Black", 3, 16)); // NOI18N
        clbtn.setForeground(new java.awt.Color(47, 47, 208));
        clbtn.setText("Clear");
        clbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dojtf, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atf, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sntf, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etf)
                                .addGap(27, 27, 27)
                                .addComponent(ttf))
                            .addComponent(ntf, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stf, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftf, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mtf, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mntf, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(clbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ntf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(ftf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etf)
                    .addComponent(ttf)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subcb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mntf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(atf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(sntf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dojtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(backbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ttfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttfActionPerformed

    private void sntfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sntfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sntfActionPerformed

    private void mntfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mntfActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
new Mainmenu().setVisible(true);
this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void etfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etfActionPerformed

    private void subcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subcbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subcbActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
new Exit().setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_exitbtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
int Class=0;
try
{
Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/new_connectivity","root","a");
Statement stmt = con.createStatement();
int Sch_No = Integer.parseInt(stf.getText());
String Name = ntf.getText();
String Date_Of_Joining = dojtf.getText();                 
 if(etf.isSelected()==true)
       Class =11;
   else
       Class =12;
 String query = "insert into basic values("+Sch_No+",'"+Name+"',"+Class+",'"+Date_Of_Joining+"');"; 
 stmt.executeUpdate(query);
 
String Father_Name = ftf.getText();
String Mother_Name = mtf.getText();
String Subject = (String)subcb.getSelectedItem();
String Mobile_No = mntf.getText();
String Address = atf.getText();
String School_Name = sntf.getText();
String quer = "insert into private values("+Sch_No+",'"+Father_Name+"','"+Mother_Name+"','"+Mobile_No+"','"+School_Name+"','"+Address+"','"+Subject+"');";
stmt.executeUpdate(quer);

JOptionPane.showMessageDialog(null,"Database Connect Successfully"); 
}
catch (Exception e)
{
 JOptionPane.showMessageDialog(null,"Database Not Found");     
 }
    }//GEN-LAST:event_addbtnActionPerformed

    private void atfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atfActionPerformed

    private void clbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clbtnActionPerformed
stf.setText("");
ntf.setText("");
ftf.setText("");
mtf.setText("");
mntf.setText("");
atf.setText("");
sntf.setText("");
dojtf.setText("");

    }//GEN-LAST:event_clbtnActionPerformed

    private void dojtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dojtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dojtfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JTextField atf;
    private javax.swing.JButton backbtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton clbtn;
    private javax.swing.JTextField dojtf;
    private javax.swing.JRadioButton etf;
    private javax.swing.JButton exitbtn;
    private javax.swing.JTextField ftf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField mntf;
    private javax.swing.JTextField mtf;
    private javax.swing.JTextField ntf;
    private javax.swing.JTextField sntf;
    private javax.swing.JTextField stf;
    private javax.swing.JComboBox subcb;
    private javax.swing.JRadioButton ttf;
    // End of variables declaration//GEN-END:variables
}
