
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sfs
 */
public class Delete extends javax.swing.JFrame {

    /**
     * Creates new form dELETE
     */
    public Delete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        subcb4 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        dojtf = new javax.swing.JTextField();
        stf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sntf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ntf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        mtf = new javax.swing.JTextField();
        exitbtn = new javax.swing.JButton();
        ftf = new javax.swing.JTextField();
        backbtn = new javax.swing.JButton();
        atf = new javax.swing.JTextField();
        deletebtn = new javax.swing.JButton();
        mntf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        searchbtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        ctf = new javax.swing.JTextField();
        subtf = new javax.swing.JTextField();
        clbtn = new javax.swing.JButton();

        subcb4.setFont(new java.awt.Font("URW Palladio L", 3, 18)); // NOI18N
        subcb4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Science with Maths", "Science with Bio", "Science with IP" }));
        subcb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subcb4ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("DejaVu Sans Light", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(32, 66, 118));
        jLabel11.setText("Subject");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dojtf.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        dojtf.setForeground(new java.awt.Color(0, 0, 102));

        stf.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        stf.setForeground(new java.awt.Color(0, 0, 102));
        stf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stfActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans Light", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(54, 54, 193));
        jLabel1.setText("Enter The Sch_No. ");

        jLabel7.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(14, 31, 156));
        jLabel7.setText("Date Of Joining");

        sntf.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        sntf.setForeground(new java.awt.Color(0, 0, 102));
        sntf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sntfActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(14, 31, 156));
        jLabel6.setText("Mobile No.");

        jLabel8.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(14, 31, 156));
        jLabel8.setText("Class");

        ntf.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        ntf.setForeground(new java.awt.Color(0, 0, 102));

        jLabel10.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(14, 31, 156));
        jLabel10.setText("School Name");

        mtf.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        mtf.setForeground(new java.awt.Color(0, 0, 102));

        exitbtn.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(25, 145, 24));
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        ftf.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        ftf.setForeground(new java.awt.Color(0, 0, 102));

        backbtn.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        backbtn.setForeground(new java.awt.Color(25, 145, 24));
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        atf.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        atf.setForeground(new java.awt.Color(0, 0, 102));

        deletebtn.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        deletebtn.setForeground(new java.awt.Color(25, 145, 24));
        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        mntf.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        mntf.setForeground(new java.awt.Color(0, 0, 102));
        mntf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntfActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(14, 31, 156));
        jLabel5.setText("Mother's Name");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(14, 31, 156));
        jLabel3.setText("Address");

        jSeparator1.setBackground(new java.awt.Color(130, 48, 96));
        jSeparator1.setForeground(new java.awt.Color(157, 29, 90));
        jSeparator1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(66, 50, 176));
        jLabel2.setText("Name");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(14, 31, 156));
        jLabel4.setText("Father's Name");

        jLabel9.setFont(new java.awt.Font("URW Chancery L", 3, 40)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(232, 29, 129));
        jLabel9.setText("DC Coaching Classes");

        searchbtn.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        searchbtn.setForeground(new java.awt.Color(25, 145, 24));
        searchbtn.setText("SEARCH");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("DejaVu Sans Light", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(32, 66, 118));
        jLabel12.setText("Subject");

        ctf.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        ctf.setForeground(new java.awt.Color(0, 0, 102));
        ctf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctfActionPerformed(evt);
            }
        });

        subtf.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        subtf.setForeground(new java.awt.Color(0, 0, 102));
        subtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtfActionPerformed(evt);
            }
        });

        clbtn.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        clbtn.setForeground(new java.awt.Color(25, 145, 24));
        clbtn.setText("Clear");
        clbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel6))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dojtf, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sntf, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mntf, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(atf, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2))
                            .addComponent(jLabel12))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ntf, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftf, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ctf, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mtf, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subtf, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stf, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deletebtn)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ntf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ftf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mtf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(clbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ctf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subtf, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(mntf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(atf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sntf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dojtf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sntfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sntfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sntfActionPerformed

    private void subcb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subcb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subcb4ActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
new Mainmenu().setVisible(true);
this .dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
new Exit().setVisible(true);
    this.setVisible(false);     
    }//GEN-LAST:event_exitbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
try
{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/new_connectivity","root","a");
Statement stmt = con.createStatement();
int Sch_No=Integer.parseInt(stf.getText());
String query="delete from basic where Sch_No = '"+Sch_No+"';";
stmt.executeUpdate(query);

String quer="delete from private where Sch_No = '"+Sch_No+"';";
stmt.executeUpdate(quer);
deletebtn.setEnabled(true);
        stf.setText("");
        ntf.setText("");
        ftf.setText("");
        mtf.setText("");
        mntf.setText("");
        atf.setText("");
        sntf.setText("");
        dojtf.setText("");
        ctf.setText("");
        subtf.setText("");
JOptionPane.showMessageDialog(null,"Record Deleted Succesfully");
}
catch (Exception e)

{
    JOptionPane.showMessageDialog(null,"Error in Conectivity");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_deletebtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/new_connectivity","root","a");
Statement stmt = con.createStatement();
String Sch_No=stf.getText();
String query="Select * from basic where Sch_No='"+Sch_No+"';";

ResultSet rs=stmt.executeQuery(query);
while(rs.next())
{
String Name =rs.getString("Name");
String Class=rs.getString("Class");
String Date_Of_Joining=rs.getString("Date_Of_Joining");
ntf.setText(""+Name);
ctf.setText(""+Class);
dojtf.setText(""+Date_Of_Joining);
}

String quer="Select * from private where Sch_No='"+Sch_No+"';";
ResultSet rp=stmt.executeQuery(quer);
while (rp.next())
{
String Father_Name =rp.getString("Father_Name");
String Mother_Name =rp.getString("Mother_Name");
String Mobile_No =rp.getString("Mobile_No");
String School_Name =rp.getString("School_Name");
String Address =rp.getString("Address");
String Subject=rp.getString("Subject");
ftf.setText(""+Father_Name);
mtf.setText(""+Mother_Name);
mntf.setText(""+Mobile_No);
sntf.setText(""+School_Name);
atf.setText(""+Address);
subtf.setText(""+Subject);
}
JOptionPane.showMessageDialog(null,"Database Connect Successfully");
}
catch (Exception e) {
JOptionPane.showMessageDialog(null,"Database Not Found");
        }         // TODO add your handling code here:

    }//GEN-LAST:event_searchbtnActionPerformed

    private void subtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtfActionPerformed

    private void clbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clbtnActionPerformed
        stf.setText("");
        ntf.setText("");
        ftf.setText("");
        mtf.setText("");
        mntf.setText("");
        atf.setText("");
        sntf.setText("");
        dojtf.setText("");
        ctf.setText("");
        subtf.setText("");
        
    }//GEN-LAST:event_clbtnActionPerformed

    private void stfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stfActionPerformed

    private void mntfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mntfActionPerformed

    private void ctfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField atf;
    private javax.swing.JButton backbtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clbtn;
    private javax.swing.JTextField ctf;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField dojtf;
    private javax.swing.JButton exitbtn;
    private javax.swing.JTextField ftf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField mntf;
    private javax.swing.JTextField mtf;
    private javax.swing.JTextField ntf;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField sntf;
    private javax.swing.JTextField stf;
    private javax.swing.JComboBox subcb4;
    private javax.swing.JTextField subtf;
    // End of variables declaration//GEN-END:variables
}
