
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sfs
 */
public class Edit extends javax.swing.JFrame {

    /**
     * Creates new form Edit
     */
    public Edit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        mntf = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sntf = new javax.swing.JTextField();
        mtf = new javax.swing.JTextField();
        ntf = new javax.swing.JTextField();
        stf = new javax.swing.JTextField();
        atf = new javax.swing.JTextField();
        backbtn = new javax.swing.JButton();
        ftf = new javax.swing.JTextField();
        exitbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        searchbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        dojtf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ctf = new javax.swing.JTextField();
        subtf = new javax.swing.JTextField();
        clbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("URW Chancery L", 3, 40)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(232, 29, 129));
        jLabel9.setText("DC Coaching Classes");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(66, 50, 176));
        jLabel2.setText("Name");

        jSeparator1.setForeground(new java.awt.Color(9, 4, 4));
        jSeparator1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mntf.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        mntf.setForeground(new java.awt.Color(14, 31, 156));
        mntf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntfActionPerformed(evt);
            }
        });

        savebtn.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(14, 31, 156));
        jLabel3.setText("Address");

        jLabel5.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(14, 31, 156));
        jLabel5.setText("Mother Name");

        jLabel6.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(14, 31, 156));
        jLabel6.setText("Mobile No.");

        jLabel8.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(14, 31, 156));
        jLabel8.setText("Class");

        sntf.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        sntf.setForeground(new java.awt.Color(14, 31, 156));
        sntf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sntfActionPerformed(evt);
            }
        });

        mtf.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        mtf.setForeground(new java.awt.Color(14, 31, 156));

        ntf.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        ntf.setForeground(new java.awt.Color(14, 31, 156));
        ntf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntfActionPerformed(evt);
            }
        });

        stf.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        stf.setForeground(new java.awt.Color(14, 31, 156));
        stf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stfActionPerformed(evt);
            }
        });

        atf.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        atf.setForeground(new java.awt.Color(14, 31, 156));
        atf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atfActionPerformed(evt);
            }
        });

        backbtn.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        backbtn.setForeground(new java.awt.Color(14, 14, 19));
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        ftf.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        ftf.setForeground(new java.awt.Color(14, 31, 156));
        ftf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfActionPerformed(evt);
            }
        });

        exitbtn.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans Light", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(54, 54, 193));
        jLabel1.setText("Enter The Sch_No. ");

        searchbtn.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        searchbtn.setText("SEARCH");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(14, 31, 156));
        jLabel4.setText("Father Name");

        dojtf.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        dojtf.setForeground(new java.awt.Color(14, 31, 156));
        dojtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dojtfActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(14, 31, 156));
        jLabel7.setText("Date Of Joining");

        jLabel10.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(14, 31, 156));
        jLabel10.setText("School Name");

        jLabel11.setFont(new java.awt.Font("DejaVu Sans Light", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(32, 66, 118));
        jLabel11.setText("Subject");

        ctf.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        ctf.setForeground(new java.awt.Color(14, 31, 156));

        subtf.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        subtf.setForeground(new java.awt.Color(14, 31, 156));

        clbtn.setFont(new java.awt.Font("DejaVu Sans Light", 3, 16)); // NOI18N
        clbtn.setText("Clear");
        clbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(453, 453, 453))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dojtf)
                                    .addComponent(sntf)
                                    .addComponent(atf)
                                    .addComponent(mntf)
                                    .addComponent(subtf)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel4))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ftf, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                    .addComponent(ctf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ntf)
                                    .addComponent(mtf))))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ntf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mtf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(ctf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(subtf, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mntf, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sntf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dojtf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sntfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sntfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sntfActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
 
try
{
Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/new_connectivity","root","a");
Statement stmt = con.createStatement();
int Sch_No = Integer.parseInt(stf.getText());
String Name = ntf.getText();
String Date_Of_Joining = dojtf.getText();
int Class =Integer.parseInt(ctf.getText());
String query = "UPDATE basic SET Name = '"+Name+"',Class = "+Class+",Date_Of_Joining = '"+Date_Of_Joining+"' where Sch_No = "+Sch_No+";";
stmt.executeUpdate(query);

String Father_Name = ftf.getText();
String Mother_Name = mtf.getText();
String Mobile_No = mntf.getText();
String Address = atf.getText();
String School_Name = sntf.getText();
String Subject = subtf.getText();
String quer = "UPDATE private SET Father_Name = '"+Father_Name+"',Mother_Name = '"+Mother_Name+"',Mobile_No = '"+Mobile_No+"',School_Name = '"+School_Name+"',Address = '"+Address+"',Subject = '"+Subject+"' where Sch_No = "+Sch_No+";";
stmt.executeUpdate(quer);

JOptionPane.showMessageDialog(null,"Database Connect Successfully");
}
catch (Exception e)
{
 JOptionPane.showMessageDialog(null,"Database Not Found");     
 }        // TODO add your handling code here:
    }//GEN-LAST:event_savebtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
new Mainmenu().setVisible(true);
this .dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
new Exit().setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_exitbtnActionPerformed

    private void mntfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mntfActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/new_connectivity","root","a");
Statement stmt = con.createStatement();
String Sch_No=stf.getText();
String query="Select * from basic where Sch_No='"+Sch_No+"';";
ResultSet rs=stmt.executeQuery(query);
while(rs.next())
{
String Name =rs.getString("Name");
String Class=rs.getString("Class");
String Date_Of_Joining=rs.getString("Date_Of_Joining");
ntf.setText(""+Name);
ctf.setText(""+Class);
dojtf.setText(""+Date_Of_Joining);
}
String quer="Select * from private where Sch_No='"+Sch_No+"';";
ResultSet rp=stmt.executeQuery(quer);
while (rp.next())
{
String Father_Name =rp.getString("Father_Name");
String Mother_Name =rp.getString("Mother_Name");
String Mobile_No =rp.getString("Mobile_No");
String School_Name =rp.getString("School_Name");
String Address =rp.getString("Address");
String Subject =rp.getString("Subject");
ftf.setText(""+Father_Name);
mtf.setText(""+Mother_Name);
mntf.setText(""+Mobile_No);
sntf.setText(""+School_Name);
atf.setText(""+Address);
subtf.setText(""+Subject);
}
JOptionPane.showMessageDialog(null,"Database Connect Successfully");
}
catch (Exception e) {
JOptionPane.showMessageDialog(null,"Database Not Found");
        }      
    }//GEN-LAST:event_searchbtnActionPerformed

    private void atfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atfActionPerformed

    private void dojtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dojtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dojtfActionPerformed

    private void clbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clbtnActionPerformed
        stf.setText("");
        ntf.setText("");
        ftf.setText("");
        mtf.setText("");
        mntf.setText("");
        atf.setText("");
        sntf.setText("");
        dojtf.setText("");
        ctf.setText("");
        subtf.setText("");
    }//GEN-LAST:event_clbtnActionPerformed

    private void stfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stfActionPerformed

    private void ftfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfActionPerformed

    private void ntfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ntfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField atf;
    private javax.swing.JButton backbtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clbtn;
    private javax.swing.JTextField ctf;
    private javax.swing.JTextField dojtf;
    private javax.swing.JButton exitbtn;
    private javax.swing.JTextField ftf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField mntf;
    private javax.swing.JTextField mtf;
    private javax.swing.JTextField ntf;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField sntf;
    private javax.swing.JTextField stf;
    private javax.swing.JTextField subtf;
    // End of variables declaration//GEN-END:variables
}
